### ISSUE TITLE
Android benchmark 

### ISSUE THREAD

**Issue by KnIfER** [paulo-coutinho/pdfium-lib#20]
Just let you know

A simple test: 

https://github.com/KnIfER/LibPDFium#benchmarks

**Comment by prsolucoes** [comment]
Hi. 

Very nice @KnIfER :)

Do you have any simple project that use the built files to load a single PDF file and render their pages?

I want a simple project only to make unit tests.

Thanks anyway.

**Comment by KnIfER** [comment]
https://github.com/KnIfER/PDFium-Android-Demo/blob/5529a56e43fa3fd76c74838ecd93301d4a0a27a7/PDocViewer/src/main/java/com/knizha/PDocViewer/PDocMainActivity.java#L119

It's just [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) using the new pdfium.so.  

libpdfium.cr.so is compatible. but since AndroidPdfViewer is using an older version, the [JNI source](https://github.com/KnIfER/PDFium-Android-Demo/blob/main/LibPdfium/src/main/cpp/mainJNILib.cpp) should be modified slightly (`FPDFDest_GetPageIndex` -> `FPDFDest_GetPageIndex`). 

![image (7)](https://user-images.githubusercontent.com/11593903/98172508-dc512d00-1f34-11eb-8cbf-5c2b55d690e7.png)

In [Java](https://github.com/KnIfER/PDFium-Android-Demo/blob/5529a56e43fa3fd76c74838ecd93301d4a0a27a7/LibPdfium/src/main/java/com/shockwave/pdfium/PdfiumCore.java#L26), only the `pdfium-lib.so` is specifically loaded, linked dependencies will be loaded automcatically. So in my demo project, once you have built the [jni layer](https://github.com/KnIfER/PDFium-Android-Demo/tree/main/LibPdfiumSep/src/main/jni), you can easily replace `libpdfium.so` with whaterever you want, as long as the substitute has the same API.

**Comment by paulo-coutinho** [comment]
Hi @KnIfER,

Can you make any new benchmark with current version?

Thanks.

**Comment by KnIfER** [comment]
This [commit](https://github.com/lukas-w/pdfium/tree/7726a581626bbb72d6ab294ae1adbad4ca10dfb0) adopted more custom Alloc methods, which seems to slower the test by 100ms. But when I cleaned up the mobile space, I found that the "regression" becames very small, so I chose to [delete them](https://github.com/KnIfER/LibPDFium/commit/a0bf41d729bb601a2390f021402f89b890e73c03).

Anyway the new test results:

- 650ms yours v1.0.0
- 645~660ms yours  v4408

- 656~663ms my 1(ndk)
- 590~620ms my 2(visual studio)


- 620~650ms [Another guy's lib](https://github.com/KnIfER/LibPDFium/files/5554441/libpdfsdk.zip)

**Comment by paulo-coutinho** [comment]
Ok, nice. Now im using params to it link everything and generate final library.

I will close this but you can reopen if you want.
