### ISSUE TITLE
Build WASM module

### ISSUE THREAD

**Issue by amit777** [paulo-coutinho/pdfium-lib#22]
There seems to be a way to build PDFium using emscripten. Here is a link to the note that provides some hints:  https://bugs.chromium.org/p/chromium/issues/detail?id=804907

Would it be possible to add that build target to this project?

**Comment by paulo-coutinho** [comment]
Hi,

I have added it to branch:
https://github.com/paulo-coutinho/pdfium-lib/tree/support-wasm

This is the first log, but it have some erros. But im tired to continue trying and break my head for now. A lot of hours trying to compile it. I added all to the branch and will continue later.

https://github.com/paulo-coutinho/pdfium-lib/runs/1760755099?check_suite_focus=true

All files are compiled and .a file was generated, but it is not recognized by the compiler on "test" step and i verified that it too small.

Consider donation on Sponsor button.

Thanks.

**Comment by paulo-coutinho** [comment]
I have added a discussion here:
https://groups.google.com/g/pdfium/c/1dCITljJuZg

**Comment by amit777** [comment]
pdfium-wasm npm module may provide some hints on how to get it to build.

**Comment by paulo-coutinho** [comment]
Yes, im checking it to understand how it works and apply here. Thanks.

**Comment by paulo-coutinho** [comment]
I have made it work. It is here: https://github.com/paulo-coutinho/pdfium-lib/tree/support-wasm

I will merge soon.

The test app is working:

![emscripten-demo](https://user-images.githubusercontent.com/395096/106335461-a093de00-626b-11eb-96b8-76662dbe2fc8.png)

Im only with a problem when run standalone module and a index.html template to load it (pdfium.wasm).

You can test here:
https://paulo-coutinho.github.io/pdfium-lib/

Do you know about node/js to help me made it work standalone?

**Comment by paulo-coutinho** [comment]
Hi @amit777,

Finally i made it works:
https://paulo-coutinho.github.io/pdfium-lib/

Consider donation on Sponsor button.

When all builds finished i will merge it.

Thanks.

**Comment by amit777** [comment]
Thanks! I will take a closer look soon! I'm curious why you started this project? We may have a larger project, and are looking for someone to assist part time. We want to create a web pdfviewer similar to PDFjs, but using PDFium as the rendering engine.

**Comment by paulo-coutinho** [comment]
Hi,

I ported it to some platforms because someone paid me for it in the past and until now i was paid with donations to make some adjusts.

Is too hard find people that know pdfium project to work with it, so i help community with my knowledge as i can.

Thanks.

**Comment by amit777** [comment]
Thanks!  The test URL doesn't seem to working anymore at https://paulo-coutinho.github.io/pdfium-lib/

**Comment by paulo-coutinho** [comment]
Hi,

Can you test again. Because here is working nice.

Thanks.

**Comment by amit777** [comment]
The link works for me now. Thanks!  I will review and create pull request to add more js API hooks as well.

**Comment by paulo-coutinho** [comment]
Hi @amit777,

Everything is working well now.

I have added the rendering part to the page at:
https://paulo-coutinho.github.io/pdfium-lib/

You can now see the pages of the PDF.

Consider donation on Sponsor button.

Thanks.

**Comment by paulo-coutinho** [comment]
Hi @amit777,

Can i close it?

Thanks.
