### ISSUE TITLE
Android build do not create libpdfium.so

### ISSUE THREAD

**Issue by GayashanR** [paulo-coutinho/pdfium-lib#25]
Android build is not working. Creating a libpdfium.cr.so instead of libpdfium.so. Therefore testing are failing too.

**Comment by paulo-coutinho** [comment]
Hi,

In this post people use it without problem for a benchmark:
https://github.com/paulo-coutinho/pdfium-lib/issues/20

The Android build is automated and generated fine:
https://github.com/paulo-coutinho/pdfium-lib/actions/workflows/android.yml

Thanks

**Comment by paulo-coutinho** [comment]
Hi @GayashanR,

It solve your issue?

**Comment by paulo-coutinho** [comment]
Hi,

This problem was solved?

Thanks.

**Comment by paulo-coutinho** [comment]
Hi @GayashanR,

It was solved?

Thanks.

**Comment by GayashanR** [comment]
Sorry for the delay, this was solved.

**Comment by paulo-coutinho** [comment]
Hi,

@GayashanR if you have a small sample, can you share? Initializing and loading any PDF to i make some tests.

Thanks.
