### ISSUE TITLE
patch for iOS is broken

### ISSUE THREAD

**Issue by RalphBergmannKMB** [paulo-coutinho/pdfium-lib#44]
**Describe the bug**

I'm using current `master` (fdd23b782e2a9667bc4f596910cdd4f8bc46e58e)

```
$ python3 make.py run patch-ios
> Validating data...
> Patching...
> Applied: Build GN
> Applied: Deprecated Warning
> Applied: Lib JPEG
> Applied: iOS Automatically Manage Certs
> Skipped: Compiler
> Applied: Carbon
> Applied: Carbon - Font
> Applied: iOS Simulator
> Applied: 32bits constexpr
> Applied: ARM Neon
> Applied: Core FXGE
```

**To Reproduce**

follow steps to build for iOS

**Problem 1**
https://github.com/paulo-coutinho/pdfium-lib/blob/master/modules/ios.py#L119
tries to path line 1703 but I guess it should be line 1705

**Problem 2**
https://github.com/paulo-coutinho/pdfium-lib/blob/master/modules/ios.py#L177
tries to path line 951. this breaks the `if` and results in:
```
ERROR at //build/config/ios/rules.gni:982:1: Unexpected token '}'
```

**System (please complete the following information):**
 - OS: macOS
 - Version 11.5.1

**Comment by paulo-coutinho** [comment]
Hi,

I made a new release with this fix:
https://github.com/paulo-coutinho/pdfium-lib/releases

Thanks.
