### ISSUE TITLE
Clang 13 required

### ISSUE THREAD

**Issue by RalphBergmannKMB** [paulo-coutinho/pdfium-lib#45]
For a few days, the Chromium developers are using `-ffile-compilation-dir=` instead of `-fdebug-compilation-dir=`, see
https://source.chromium.org/chromium/chromium/src/+/34a955823630096f5b01c2b01d51c1ea59d22763

But this `-ffile-compilation-dir=` was introduced with Clang 13 (https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-ffile-compilation-dir).

On my Mac with macOS 11.5.1 I have Clang 12:
```
clang++ --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I guess there is a way to update Clang without waiting for Apple to do this. Can you please update the build documentation on how to do this?

**Comment by paulo-coutinho** [comment]
Hi,

I don't understand. This is how i see today:

![image](https://user-images.githubusercontent.com/395096/128372887-728203ee-8c93-47e2-9d00-7da358318eaf.png)

You want change from `-fdebug-compilation-dir` to `-ffile-compilation-dir`? Like this:

![image](https://user-images.githubusercontent.com/395096/128373211-c2beb3a1-3c67-4465-bbb2-596fd6e7d466.png)

**Comment by RalphBergmannKMB** [comment]
I downloaded it again, but still have a difference.

<img width="1083" alt="CleanShot 2021-08-05 at 17 22 37@2x" src="https://user-images.githubusercontent.com/47594120/128376426-548e00ab-2d44-46f9-89c4-4bffa8993e16.png">

`git status` show that I have this version https://chromium.googlesource.com/chromium/src/build.git/+/1ae483ee7

When I revert the changes from this commit, I can build the library.
https://source.chromium.org/chromium/chromium/src/+/34a955823630096f5b01c2b01d51c1ea59d22763:build/config/compiler/BUILD.gn;dlc=b283335cc5579f0105a4df08aca9e9b53d7b4196

**Comment by paulo-coutinho** [comment]
Hi,

Can you add a patch to the project?

Only need add something like this:
https://github.com/paulo-coutinho/pdfium-lib/blob/master/modules/ios.py#L225-L232

My code not tested:

```
# clang 12
source_file = os.path.join(
    source_dir,
    "build",
    "config",
    "compiler",
    "BUILD.gn",
)
if f.file_line_has_content(source_file, 1230, "      cflags += [ "-ffile-compilation-dir=." ]\n"):
    f.replace_line_in_file(source_file, 1230, "      cflags += ["-Xclang","-fdebug-compilation-dir","-Xclang",".",]\n")

    f.debug("Applied: Clang 12")
else:
    f.debug("Skipped: Clang 12")
```

Put after latest patch on file "ios.py".

After you try, please, let me know if you have success.

**Comment by paulo-coutinho** [comment]
Hi,

I made a new release with this fix:
https://github.com/paulo-coutinho/pdfium-lib/releases

Thanks.
