### ISSUE TITLE
M1 Build iOS/MacOS failed(4599)

### ISSUE THREAD

**Issue by zenghao0708** [paulo-coutinho/pdfium-lib#52]
**Describe the bug**
M1 Build iOS/MacOS failed(4599)

**To Reproduce**
Run all the steps, but failed when run 'python3 make.py run build-macos'

**Screenshots**
pdfium-lib git:(ec317c7) python3 make.py run build-macos
> Validating data...
> Building libraries...
> Generating files to arch "x64" and configuration "release"...
ERROR at //third_party/zlib/BUILD.gn:506:1: Expecting assignment or function call.
}
^
Traceback (most recent call last):
  File "/Users/zenghao/Git_Repos/Tools/PDF/pdfium-lib/make.py", line 243, in <module>
    main(args)
  File "/Users/zenghao/Git_Repos/Tools/PDF/pdfium-lib/make.py", line 146, in main
    macos.run_task_build()
  File "/Users/zenghao/Git_Repos/Tools/PDF/pdfium-lib/modules/macos.py", line 161, in run_task_build
    check_call(command, shell=True)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gn gen out/macos-x64-release --args='target_os="mac" target_cpu="x64" use_goma=false is_debug=false pdf_use_skia=false pdf_use_skia_paths=false pdf_enable_xfa=false pdf_enable_v8=false is_component_build=false clang_use_chrome_plugins=false pdf_is_standalone=true use_xcode_clang=false pdf_is_complete_lib=true use_custom_libcxx=false use_sysroot=false symbol_level=0'' returned non-zero exit status 1.

**System (please complete the following information):**
 - OS: MacOS 12.0.1（M1）
 - Target [e.g. iOS、MacOS]

**Additional context**

here are some software version:
➜  pdfium-lib git:(ec317c7) ninja --version
1.10.2
➜  pdfium-lib git:(ec317c7) python3 --version
Python 3.9.6
➜  pdfium-lib git:(ec317c7) pip3 --version
pip 21.1.3 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)

**Comment by paulo-coutinho** [comment]
Hi,

I launched a new version (4692). 

To test, you can access:
https://pdfviewer.github.io/

Can you check the docs/code to see if your problem still happen?

You can donate, if you want, to help the project.

Thanks.

**Comment by zenghao0708** [comment]
@paulo-coutinho it works with version 4592. Cool, thanks~~
