### ISSUE TITLE
cannot launch android application whith libirary

### ISSUE THREAD

**Issue by MohamedAshraf9** [paulo-coutinho/pdfium-lib#60]
I have error : dlopen failed: library libabsl.cr.so not found when launch app with android studio

**Comment by paulo-coutinho** [comment]
Hi,

Probably you will need load all libraries inside lib folder:

![image](https://user-images.githubusercontent.com/395096/146824289-c5407d0a-5c95-4e40-9da7-6f4d6d4e2bc7.png)

Like here:
https://stackoverflow.com/questions/8828559/loading-3rd-party-shared-libraries-from-an-android-native-activity

Use the correct order, since pdfium need be the last library to be loaded.

**Comment by MohamedAshraf9** [comment]
This is what I did and the error is still there

**Comment by paulo-coutinho** [comment]
Hi,

I made a project showing it working:
https://www.dropbox.com/s/s7u1tc35v74eil5/TestNative.zip?dl=1

Thanks.

**Comment by MohamedAshraf9** [comment]
how it works with CMakeLists and c++ ?
it didn't work with it

**Comment by paulo-coutinho** [comment]
Yes, it work, but you need study. 

I made a project with cmake to you understand:
https://www.dropbox.com/s/xr1cfijhuadbxu8/TestNativeCmake.zip?dl=1

**Comment by MohamedAshraf9** [comment]
thank you very much ,it works with me ,but after render pdf, app appears pdf and then crash and show me this error :
 A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfba3 in tid 5578 (PDF renderer), pid 5551

**Comment by paulo-coutinho** [comment]
Nice!

You need share your source code, because it is a generic error message.

If you have a project, put it here zipped.

Feel free to support the project with donations on sponsor project.

**Comment by paulo-coutinho** [comment]
Did you solved your problem? Can i close?

**Comment by MohamedAshraf9** [comment]
I'm really sorry for the delay,
Yes I solved it You can close
